server:
  port: ${PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:cce-challenge}
    jackson:
      time-zone: America/Recife

  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cce-challenge}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update


  servlet:
    multipart:
      max-file-size: 999999999999999999
      max-request-size: 999999999999999999
